/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "../rrc.asn1"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_InitialUE_Identity_H_
#define	_InitialUE_Identity_H_

typedef enum InitialUE_Identity_PR {
	InitialUE_Identity_PR_NOTHING,	/* No components present */
	InitialUE_Identity_PR_imsi,
	InitialUE_Identity_PR_tmsi_and_LAI,
	InitialUE_Identity_PR_p_TMSI_and_RAI,
	InitialUE_Identity_PR_imei,
	InitialUE_Identity_PR_esn_DS_41,
	InitialUE_Identity_PR_imsi_DS_41,
	InitialUE_Identity_PR_imsi_and_ESN_DS_41,
	InitialUE_Identity_PR_tmsi_DS_41
} InitialUE_Identity_PR;


#endif	/* _InitialUE_Identity_H_ */

